### PR TITLE
Update aws.md

### PR DESCRIPTION
**Pull request by JustinN-Replicated**
Preview: https://deploy-preview-794--kurlsh-staging.netlify.app/docs/add-ons/aws

### CODE REVIEW

**Review by jonquil2002 — APPROVED** [review]
LGTM. Suggested a formatting change. Please feel free to merge if you are good with it.

**Review by jonquil2002 — APPROVED** [review]
LGTM with a minor wording change to avoid "use/using" twice. Also adds more specificity.

**Review by JustinN-Replicated — COMMENTED** [review]
added many links to amazon docs and kubernetes add-on for default cluster name

**Review by jonquil2002 — DISMISSED** [review]
Made some edits.

**Review by jonquil2002 — DISMISSED** [review]
lgtm

**Review by jonquil2002 — APPROVED** [review]
In the flags-table, or excludeStorageClass, you need to change aws to either AWS or `aws`.

Hope this helps :)

**Review by jonquil2002 — DISMISSED** [review]
lgtm. The link doesn't work in this table, but you already know there is a bug.

**Comment by JustinN-Replicated** [comment]
Link should work in the table, but not on the mouse over (i) bubble on kurl.sh page. Will investigate this now.

**Review by jonquil2002 — APPROVED** [review]
lgtm

**Comment by jonquil2002** [comment]
@JustinN-Replicated  I reviewed your latest changes and committed a bunch of my own editing changes for you.

**Comment by JustinN-Replicated** [comment]
Thank you @jonquil2002; likely that this one will be on hold for a bit but we are shaping up here.

**Review by jonquil2002 — DISMISSED** [review]
Approved with my latest changes.

**Comment by JustinN-Replicated** [comment]
@jala-dx we should review this together when we pair this week. Like I mentioned yesterday, it is my understanding that the kubernetes aws-cloud-provider interacts with the aws apis and kubeadm; having said that, from the items that are open it sounds like it may be more than just permission details to get the whole breadth of functionality from the component.

**Review by jonquil2002 — APPROVED** [review]
lgtm - made one minor edit.

**Comment by JustinN-Replicated** [comment]
@jala-dx I know you are going to give this one more review, but also wanted to mention that if everything looks technically accurate I think we should merge when we can; afaik no reason to wait for anything for this one as these details apply to what is there already (although some of the bugs will need to be merged to be addressed, since this is beta and these docs are a big improvement we should try to get them out sooner rather than later). 

@jdewinne definitely do want to iterate on this if needed though so please feel free to let us know other places we can improve.

**Pull request merged**
