### PR TITLE
Update local-path-provisioner.md

### PR DESCRIPTION
**Pull request by JustinN-Replicated**

### CODE REVIEW

**Review by paigecalvert — APPROVED** [review]
thanks @JustinN-Replicated !!

**Comment by JustinN-Replicated** [comment]
@jonquil2002 @paigecalvert @laverya 
I am unsure if we also want to specifically mention the current limitation with localpv on the velero add-on page too or just link to the limitations they have published and call it a day - wdyat? I think just link to the limitations in general since @laverya has mentioned possible contributing to velero to remedy their limitation maybe (if I followed the slack thread correctly from yesterday)

**Comment by JustinN-Replicated** [comment]
@jonquil2002 @paigecalvert @laverya I think this was approved prior to my last comment - looking for feedback  to that comment before merging. Please let me know :)

**Review by jonquil2002 — APPROVED** [review]
lgtm

**Pull request merged**
