### PR TITLE
add hostname and IP address requirements

### PR DESCRIPTION
**Pull request by adamancini**
make sure machine names are valid DNS domains according to kubernetes requirements, that they resolve in DNS, and do not change IP address or hostname

sc-68464

### CODE REVIEW

**Review by paigecalvert — APPROVED** [review]
Looks great; made some minor wording/grammar edits. (There were a couple cases where I was not sure which noun the word "it" was referring to, so feel free to correct if I got anything wrong).

Also, a few notes just for consideration:

- Language switches from "hosts" to "nodes" in line 90. Could help with clarity to use the same term throughout, if that makes sense/matters in this case.
- Since these requirements are read before one installs with kURL, is there anything to add in terms of action-items that we'd want the user to take when choosing the hostname/IP address for a node? Like, "we recommend you choose something that you don't expect needing to change", or something to that affect? Could help to spell out exactly the expectation or heads-up we want to convey 
- This is out of scope for this PR, but should the info about what steps to take to rename a node also be added to the Managing Nodes topic? I was thinking that if someone was looking for that info, they might not think to go back to Requirements

**Review by laverya — APPROVED** [review]

**Comment by adamancini** [comment]
> This is out of scope for this PR, but should the info about what steps to take to rename a node also be added to the Managing Nodes topic? I was thinking that if someone was looking for that info, they might not think to go back to Requirements

Yeah this is a good idea

**Comment by adamancini** [comment]
@paigecalvert @laverya thanks!


@paigecalvert what's this test that is required but not passing?

**Review by paigecalvert — APPROVED** [review]

**Comment by paigecalvert** [comment]
@adamancini I'm not sure, that's something the kURL team would have added. @laverya -- do you know what's going on with the "Required pull request labels" test?

**Comment by paigecalvert** [comment]
@adamancini @laverya or wait, I'm now seeing that same required pull requests thing on our Replicated Docs repo as well...not sure what that is. It looks like it wants us to add a primary label. So maybe this needs to have "feature" or "bug applied" to it as well?

**Comment by adamancini** [comment]
> @adamancini @laverya or wait, I'm now seeing that same required pull requests thing on our Replicated Docs repo as well...not sure what that is. It looks like it wants us to add a primary label. So maybe this needs to have "feature" or "bug" added to it as well?

🤷‍♀️

**Pull request merged**
