### PR TITLE
Remove Add-on Author page

### PR DESCRIPTION
**Pull request by emosbaugh**

### CODE REVIEW

**Comment by AmberAlston** [comment]
@emosbaugh I think we should talk about this change live before committing this. I know https://kurl.sh/docs/add-on-author/ is out-of-date and https://github.com/replicatedhq/kURL/blob/main/CONTRIBUTING.md should be the source of truth, but they don't seem fully comparable from a content perspective. 

Also if we're going to point folks to https://github.com/replicatedhq/kURL/blob/main/CONTRIBUTING.md we should likely also update the kurl readme to make it more discoverable. 

Let me know when you have some time to chat live early next week.

**Comment by emosbaugh** [comment]
[sc-60599]

**Review by camilamacedo86 — DISMISSED** [review]

**Review by camilamacedo86 — APPROVED** [review]
@AmberAlston, 

We moved the website content to the CONTRIBUTING.MD guide and we update the README to make clear where the info is, see: https://github.com/replicatedhq/kURL/pull/3776. PS.: Also, we have been updating the contributing guide. 

In this way, could we get this one merged?

c/c @emosbaugh

**Review by AmberAlston — APPROVED** [review]

**Comment by AmberAlston** [comment]
Should only be merged after https://github.com/replicatedhq/kURL/pull/3776 is merged and live

**Pull request merged**
